export const drinks = [
  // ── Single (1 shot ≈ 30 ml espresso, ≈ 63 mg caffeine) ────────────────
  {
    id: 'single-espresso',
    name: 'Espresso',
    category: 'single',
    caffeineMg: 63,
    recipe: {
      shots: 1,
      espressoMl: 30,
      milkMl: 0,
      milkStyle: null,
      cupSizeMl: 60,
      notes: 'Serve immediately in a pre-warmed espresso cup.',
    },
  },
  {
    id: 'single-americano',
    name: 'Americano',
    category: 'single',
    caffeineMg: 63,
    recipe: {
      shots: 1,
      espressoMl: 30,
      milkMl: 0,
      milkStyle: 'Top with 150 ml hot water',
      cupSizeMl: 210,
      notes: 'Add hot water after espresso to preserve the crema.',
    },
  },
  {
    id: 'single-cappuccino',
    name: 'Cappuccino',
    category: 'single',
    caffeineMg: 63,
    recipe: {
      shots: 1,
      espressoMl: 30,
      milkMl: 100,
      milkStyle: 'Steam to 65 °C — half steamed milk, half thick foam',
      cupSizeMl: 150,
      notes: 'Tap the jug on the counter and swirl before pouring.',
    },
  },
  {
    id: 'single-latte',
    name: 'Latte',
    category: 'single',
    caffeineMg: 63,
    recipe: {
      shots: 1,
      espressoMl: 30,
      milkMl: 200,
      milkStyle: 'Steam to 65 °C — velvety microfoam, no thick foam',
      cupSizeMl: 250,
      notes: 'Pour milk in a slow, steady stream to blend with espresso.',
    },
  },
  {
    id: 'single-flat-white',
    name: 'Flat White',
    category: 'single',
    caffeineMg: 63,
    recipe: {
      shots: 1,
      espressoMl: 30,
      milkMl: 120,
      milkStyle: 'Steam to 65 °C — ultra-silky microfoam, no thick foam layer',
      cupSizeMl: 160,
      notes: 'Smaller and stronger than a latte. Milk should be glossy.',
    },
  },
  {
    id: 'single-macchiato',
    name: 'Macchiato',
    category: 'single',
    caffeineMg: 63,
    recipe: {
      shots: 1,
      espressoMl: 30,
      milkMl: 30,
      milkStyle: 'Dollop of steamed foam on top',
      cupSizeMl: 90,
      notes: '"Macchiato" means stained — just a small mark of milk.',
    },
  },

  // ── Double (2 shots ≈ 60 ml espresso, ≈ 125 mg caffeine) ──────────────
  {
    id: 'double-espresso',
    name: 'Espresso',
    category: 'double',
    caffeineMg: 125,
    recipe: {
      shots: 2,
      espressoMl: 60,
      milkMl: 0,
      milkStyle: null,
      cupSizeMl: 90,
      notes: 'Serve immediately in a pre-warmed espresso cup.',
    },
  },
  {
    id: 'double-americano',
    name: 'Americano',
    category: 'double',
    caffeineMg: 125,
    recipe: {
      shots: 2,
      espressoMl: 60,
      milkMl: 0,
      milkStyle: 'Top with 180 ml hot water',
      cupSizeMl: 240,
      notes: 'Add hot water after espresso to preserve the crema.',
    },
  },
  {
    id: 'double-cappuccino',
    name: 'Cappuccino',
    category: 'double',
    caffeineMg: 125,
    recipe: {
      shots: 2,
      espressoMl: 60,
      milkMl: 100,
      milkStyle: 'Steam to 65 °C — half steamed milk, half thick foam',
      cupSizeMl: 180,
      notes: 'Tap the jug on the counter and swirl before pouring.',
    },
  },
  {
    id: 'double-latte',
    name: 'Latte',
    category: 'double',
    caffeineMg: 125,
    recipe: {
      shots: 2,
      espressoMl: 60,
      milkMl: 200,
      milkStyle: 'Steam to 65 °C — velvety microfoam, no thick foam',
      cupSizeMl: 300,
      notes: 'Pour milk in a slow, steady stream to blend with espresso.',
    },
  },
  {
    id: 'double-flat-white',
    name: 'Flat White',
    category: 'double',
    caffeineMg: 125,
    recipe: {
      shots: 2,
      espressoMl: 60,
      milkMl: 120,
      milkStyle: 'Steam to 65 °C — ultra-silky microfoam, no thick foam layer',
      cupSizeMl: 200,
      notes: 'Smaller and stronger than a latte. Milk should be glossy.',
    },
  },
  {
    id: 'double-macchiato',
    name: 'Macchiato',
    category: 'double',
    caffeineMg: 125,
    recipe: {
      shots: 2,
      espressoMl: 60,
      milkMl: 30,
      milkStyle: 'Dollop of steamed foam on top',
      cupSizeMl: 120,
      notes: '"Macchiato" means stained — just a small mark of milk.',
    },
  },

  // ── Luxe (Ninja specialty recipes, ≈ 1.5–2 shots) ────────────────────
  {
    id: 'luxe-latte',
    name: 'Luxe Latte',
    category: 'luxe',
    caffeineMg: 95,
    recipe: {
      shots: 1.5,
      espressoMl: 45,
      milkMl: 220,
      milkStyle: 'Steam to 65 °C — extra velvety microfoam',
      cupSizeMl: 280,
      notes: 'Ninja\'s premium latte recipe — richer and smoother than a standard latte.',
    },
  },
  {
    id: 'luxe-flat-white',
    name: 'Luxe Flat White',
    category: 'luxe',
    caffeineMg: 95,
    recipe: {
      shots: 1.5,
      espressoMl: 45,
      milkMl: 130,
      milkStyle: 'Steam to 65 °C — ultra-silky microfoam',
      cupSizeMl: 180,
      notes: 'Denser and more intense than a standard flat white.',
    },
  },
  {
    id: 'luxe-cappuccino',
    name: 'Luxe Cappuccino',
    category: 'luxe',
    caffeineMg: 95,
    recipe: {
      shots: 1.5,
      espressoMl: 45,
      milkMl: 110,
      milkStyle: 'Steam to 65 °C — generous, dense foam',
      cupSizeMl: 170,
      notes: 'Richer and more indulgent than a standard cappuccino.',
    },
  },
  {
    id: 'luxe-iced-latte',
    name: 'Iced Luxe Latte',
    category: 'luxe',
    caffeineMg: 95,
    recipe: {
      shots: 1.5,
      espressoMl: 45,
      milkMl: 200,
      milkStyle: 'Cold milk, no steaming — pour over ice',
      cupSizeMl: 300,
      notes: 'Brew espresso first, allow to cool slightly, then pour over ice and milk.',
    },
  },
  {
    id: 'luxe-iced-americano',
    name: 'Iced Americano',
    category: 'luxe',
    caffeineMg: 63,
    recipe: {
      shots: 1,
      espressoMl: 30,
      milkMl: 0,
      milkStyle: 'Pour 150 ml cold water over ice',
      cupSizeMl: 250,
      notes: 'Fill glass with ice first, then add cold water, then pour espresso on top.',
    },
  },
];

export const categories = [
  { id: 'single', label: 'Single', description: '1 shot · ≈ 30 ml espresso' },
  { id: 'double', label: 'Double', description: '2 shots · ≈ 60 ml espresso' },
  { id: 'luxe',   label: 'Luxe',   description: 'Ninja specialty recipes' },
];
